name: github-actions-demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Testing-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: python --version 

  Install-pylint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install Flask
      - run: python -m pip install --upgrade pip
      - run: pip install pylint 

     